# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
  imageName: "ubuntu-latest"
  jdk_version: "1.11"
  MAVEN_CHACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository


stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job:
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(imageName)
    steps:
    - task: Cache@2
      inputs:
        key: '''maven | "(Agent.OS)" | **/pom.xml'
        path: '$(MAVEN_CACHE_FOLDER)'
        restoreKeys: |
          maven | "$(Agent.OS)"
          maven
    - task: Maven@3
      inputs:
        mavenPomFile: "pom.xml"
        mavenOptions: "-Xmx3072m"
        options: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)"

    - publish: target
      artifact: webapp
      displayName: Publish Artifacts

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: DeployWebApp
    displayName: Deploy Web App
    pool:
      vmImage: $(imageName)
    steps:
    - checkout: none
    - download: current
      artifact: webapp

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Pipeline.Workspace)/webapp/'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Pipeline.Workspace)/$(Build.BuildId).zip'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Azure Internal Consumption(b43a5236-bbcd-474c-acb4-97b672576e3b)'
        appType: 'webAppLinux'
        appName: 'yusuzulinuxwebapp'
        package: '$(Pipeline.WorkSpace)/*.zip'